# Generated by Django 3.0.6 on 2020-05-30 22:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DTC', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('DTU', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=30)),
                ('ch', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
