# Generated by Django 3.0.6 on 2020-05-30 23:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20200531_0206'),
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='food',
            name='ch',
            field=models.FloatField(blank=True, null=True, verbose_name='Углеводы на 100г'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DTC', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('DTU', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('foods', models.ManyToManyField(related_name='records', to='calculator.Food')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='person.Person', verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
