# Generated by Django 3.0.6 on 2020-05-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20200530_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='native_lang',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='coeff_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='coeff_evening',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='coeff_morning',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='coeff_night',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='ddi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Мужской'), ('w', 'Женский')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
